CREATE SEQUENCE FileAttachmentId_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;
 
CREATE SEQUENCE WorkItemId_seq
AS BIGINT
START WITH 1000
INCREMENT BY 1;
 
CREATE SEQUENCE audit_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE audit_rule_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE rtrack_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE WIAssistantFileAttachment_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE WIAssistantComments_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE audit_core_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE view_search_info_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE security_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE turnstileFiles_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE snippetImageId_seq
AS BIGINT
START WITH 1
INCREMENT BY 1;