/* CREATE USER */

/* ricardo */

DROP USER agencyportal;
CREATE USER agencyportal
IDENTIFIED by agencyportal
DEFAULT TABLESPACE agencyportal;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE ANY INDEX,
CREATE SEQUENCE, CREATE TYPE, CREATE ANY PROCEDURE, CREATE ANY TRIGGER, EXECUTE ANY PROCEDURE to
agencyportal
WITH ADMIN OPTION;

GRANT DBA to agencyportal with admin option;

GRANT UNLIMITED TABLESPACE to agencyportal;
