CREATE SEQUENCE FileAttachmentId_seq
START WITH 1
INCREMENT BY 1;
 
CREATE SEQUENCE WorkItemId_seq
START WITH 1000
INCREMENT BY 1;
 
CREATE SEQUENCE audit_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE audit_rule_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE rtrack_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE WIAssistantFileAttachment_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE WIAssistantComments_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE audit_core_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE view_search_info_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE security_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE turnstileFiles_seq
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE snippetImageId_seq
START WITH 1
INCREMENT BY 1;